/* Static, generated indexes; no visitor-side GitHub API or credentials. */
const noticeData=window.HJPA_CONTENT||{notices:[],slides:[]};
const nb=document.getElementById('noticeBoard'),nbViewer=document.getElementById('noticeViewer'),nbLauncher=document.getElementById('noticeLauncher');
const nbMotion=window.matchMedia('(prefers-reduced-motion: reduce)');
let nbReturnFocus=null,nbViewerTrigger=null,nbCloseTimer=null,nbZoom=100;
function noticeToday(now=new Date()){const p=new Intl.DateTimeFormat('en-US',{timeZone:'America/Jamaica',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(now);return ['year','month','day'].map(k=>p.find(x=>x.type===k).value).join('-')}
function noticeIsPast(item,today=noticeToday()){return Boolean(item.date&&item.date<today)}
function refreshNoticeDates(){document.querySelectorAll('[data-notice-id]').forEach(button=>{const item=noticeData.notices.find(n=>n.id===button.dataset.noticeId);const past=noticeIsPast(item);button.classList.toggle('past',past);button.querySelector('.nb-past').hidden=!past;button.setAttribute('aria-label',item.title+(past?' — past event':'')+'; open poster')})}
function renderNoticeBoard(){const root=document.getElementById('noticePosters');root.replaceChildren();if(!noticeData.notices.length){const p=document.createElement('p');p.className='nb-message';p.textContent='No notices at the moment.';root.append(p);return}
noticeData.notices.forEach((item,i)=>{const button=document.createElement('button');button.type='button';button.className='nb-poster';button.dataset.noticeId=item.id;button.style.animationDelay=Math.min(i,6)*55+'ms';const img=document.createElement('img');img.src=item.image;img.alt=item.title+' poster';img.loading=i?'lazy':'eager';img.decoding='async';img.onerror=()=>{if(img.dataset.retried){img.hidden=true;const text=document.createElement('p');text.className='nb-message';text.textContent='Poster unavailable. Try downloading the original.';button.append(text)}else{img.dataset.retried='true';img.src=item.original}};const badge=document.createElement('span');badge.className='nb-past';badge.textContent='Past';button.append(img,badge);button.addEventListener('click',()=>openNoticePoster(item.id));root.append(button)});refreshNoticeDates()}
function openNoticeBoard(){clearTimeout(nbCloseTimer);nb.classList.remove('closing');if(nb.open)return;nbReturnFocus=document.activeElement;if(typeof toggleGia==='function')toggleGia(false);renderNoticeBoard();nb.showModal();nbLauncher.setAttribute('aria-expanded','true');document.getElementById('noticeClose').focus()}
function closeNoticeBoard(restore=true){if(!nb.open)return;if(nbViewer.open)nbViewer.close();nb.classList.add('closing');clearTimeout(nbCloseTimer);nbCloseTimer=setTimeout(()=>{nb.close();nb.classList.remove('closing');nbLauncher.setAttribute('aria-expanded','false');if(restore&&nbReturnFocus?.isConnected)nbReturnFocus.focus()},nbMotion.matches?0:220)}
function setNoticeZoom(value){nbZoom=Math.min(300,Math.max(100,value));document.getElementById('noticeFull').style.width=nbZoom+'%';document.getElementById('noticeZoomValue').textContent=nbZoom+'%'}
function openNoticePoster(id){const item=noticeData.notices.find(n=>n.id===id);if(!item)return;nbViewerTrigger=document.activeElement;document.getElementById('noticeViewerTitle').textContent=item.title;const img=document.getElementById('noticeFull');img.alt=item.title;img.style.filter=noticeIsPast(item)?'grayscale(1)':'';img.src=item.original;img.onerror=()=>{img.onerror=null;img.src=item.image};const download=document.getElementById('noticeDownload');download.href=item.original;download.download=item.filename;setNoticeZoom(100);nbViewer.showModal();document.getElementById('noticeViewerClose').focus()}
nbLauncher.addEventListener('click',openNoticeBoard);document.getElementById('noticeClose').addEventListener('click',()=>closeNoticeBoard());nb.addEventListener('cancel',e=>{e.preventDefault();closeNoticeBoard()});document.getElementById('noticeViewerClose').addEventListener('click',()=>nbViewer.close());nbViewer.addEventListener('close',()=>{if(nbViewerTrigger?.isConnected)nbViewerTrigger.focus()});document.getElementById('noticeZoomIn').addEventListener('click',()=>setNoticeZoom(nbZoom+25));document.getElementById('noticeZoomOut').addEventListener('click',()=>setNoticeZoom(nbZoom-25));
function giaEventsAnswer(){return{direct:'Open the Notice Board to browse the original HJPA posters. Past event posters appear in greyscale.',bullets:[],sources:[],actions:[giaMakeAction('Open Notice Board',()=>{toggleGia(false);openNoticeBoard()},true)]}}
// Jamaica is UTC−05:00 year-round. Recheck exactly after local midnight.
function scheduleNoticeMidnight(){const now=new Date(),today=noticeToday(now),next=new Date(today+'T00:00:00-05:00').getTime()+86400000;setTimeout(()=>{refreshNoticeDates();scheduleNoticeMidnight()},Math.max(1000,next-now.getTime()+100))}scheduleNoticeMidnight();
document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshNoticeDates()});
/* The existing two background layers retain the site's shading and crossfade CSS. */
const slideA=document.getElementById('heroA'),slideB=document.getElementById('heroB');
let slides=[...noticeData.slides],slideIndex=-1,slideFront=slideA,slideTimer=null,slideBusy=false;
const fallbackSlide={image:'notice-assets/homepage-fallback.jpg'};
function loadSlide(url){return new Promise(resolve=>{const image=new Image();const timer=setTimeout(()=>resolve(false),12000);image.onload=()=>{clearTimeout(timer);resolve(true)};image.onerror=()=>{clearTimeout(timer);resolve(false)};image.src=url})}
function preloadNextSlide(){if(slides.length>1&&!nbMotion.matches){const next=slides[(slideIndex+1)%slides.length];const image=new Image();image.src=next.image}}
async function advanceSlide(initial=false){if(slideBusy||(!initial&&(document.hidden||nbMotion.matches||slides.length<2)))return;slideBusy=true;let candidate=null;let tries=slides.length;while(tries--){slideIndex=(slideIndex+1)%slides.length;const item=slides[slideIndex];if(await loadSlide(item.image)){candidate=item;break}slides.splice(slideIndex,1);slideIndex--;}
if(!candidate){candidate=fallbackSlide;if(!await loadSlide(candidate.image)){slideBusy=false;return}}
if(initial){slideA.style.backgroundImage='url('+JSON.stringify(candidate.image)+')';slideA.style.opacity='1';slideB.style.opacity='0';slideFront=slideA}else{const next=slideFront===slideA?slideB:slideA;next.style.backgroundImage='url('+JSON.stringify(candidate.image)+')';next.style.opacity='1';slideFront.style.opacity='0';slideFront=next;}slideBusy=false;preloadNextSlide()}
function scheduleSlides(){clearInterval(slideTimer);if(!document.hidden&&!nbMotion.matches&&slides.length>1)slideTimer=setInterval(()=>advanceSlide(),7000)}
advanceSlide(true).then(scheduleSlides);document.addEventListener('visibilitychange',scheduleSlides);nbMotion.addEventListener('change',scheduleSlides);
